# Activate this profile to run against a Postgres instance.
# Example: ./gradlew bootRun --args='--spring.profiles.active=postgres'
spring.datasource.url=jdbc:postgresql://localhost:5432/dsar
spring.datasource.username=dsar
spring.datasource.password=dsar
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
